### ISSUE TITLE
PHP error: is_search was called incorrectly.

### ISSUE THREAD

**Issue by viscosho** [lightspeeddevelopment/lsx-search#11]
### Describe the bug

> PHP error: is_search was called incorrectly. Conditional query tags do not work before the query is run. Before then, they always return false. Please see Debugging in WordPress for more information. (This message was added in version 3.1.0.)

### Steps to Reproduce
1. Make sure you can see a debug log or have the log report visible.
2. Make sure LSX Search is installed and turned on.
3. Go to the admin area.
4. See error.

### Expected behavior
No PHP errors related to this plugin.

### Environment information
- All Devices.
- Plugin Version 1.3.3
- Latest WordPress Version

**Comment by jacquesvdhorst** [comment]
@viscosho I've tested this locally and LGTM.
