### ISSUE TITLE
WC Product Grid Li' width causing items to drop below each other.

### ISSUE THREAD

**Issue by jacquesvdhorst** [lightspeeddevelopment/lsx-search#6]
When checking out https://sixcats.co.za/menu/ it seems that:

`.woocommerce .facetwp-template ul.products li.product, .woocommerce-page .facetwp-template ul.products li.product` is set to 30.75%width if set to 30 it fixes the issue.

**Comment by viscosho** [comment]
This was resolved, the thing causing issues was custom style on the child theme, and it was fixed there. LSX layout works ok. Closing.
