### ISSUE TITLE
Implement new and improve search results designs

### ISSUE THREAD

**Issue by ashleyshaw** [lightspeeddevelopment/lsx-search#8]
Changes to side bar filters and sort by drop downs.

Screenshot:
![Screenshot 2019-09-13 at 11 36 35](https://user-images.githubusercontent.com/31090573/64853112-0225bf00-d61b-11e9-98e8-798fbebab3bd.png)

**Comment by viscosho** [comment]
Added the collapsible options: https://github.com/lightspeeddevelopment/lsx-search/commit/fdc198684d9c9f8e851f8d0c8029abc9338c41dd
This was the only thing left for these enhancements

**Comment by viscosho** [comment]
New functionality on this Issue:

Dev - Improving search styles. (spacing, background colors, filter options)
Dev - Adding filter number to search results on mobile.
Dev - Adding search bar to mobile.
Fix - Restricted the post type labels to the global search only.
Fix - Improving footer bar.
Dev - Cosmetic improvements to Search (spacing, background colors, filter options, labels)
Dev - Making the layout for search independent from the archive layouts.
Dev - Adding collapsible facets option.

**Comment by ashleyshaw** [comment]
@garthglaum please take a look at the outcomes of this enhancement and grab some notes for our release announcement.
